name: booyahhub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  image_picker: ^1.1.2
  http: ^1.2.1
  uuid: ^4.3.3
  file_picker: ^8.1.2
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo_scrim.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_scrim.png
