name: booyahhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # All these must align vertically with 'flutter:' above
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  http: ^1.2.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
